---
driver:
  name: vagrant
  network:
    - ["forwarded_port", { guest: 80, host: 8081 }]

provisioner:
  name: chef_zero

platforms:
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[mirror::default]
    attributes:
